// 中学受験 社会 漢字書き取りドリル データ
// 四谷大塚 予習シリーズ5年下 準拠
// kosukequiz-battle側 data.js の KANJI_DATA と同じ内容・同じid体系（k{回}_{連番}）
// quiz_csv（社会通常回）が作成する 第{回}回_漢字.json をそのまま反映したもの

const KANJI_DATA = [
  // ========================================
  // 第1回：旧石器時代・縄文時代・弥生時代 (40語)
  // ========================================
  {
    id: "k1_01",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "岩宿遺跡",
    kana: "いわじゅくいせき",
    mean: "旧石器時代の存在を明らかにした遺跡（群馬県）",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_02",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "大森貝塚",
    kana: "おおもりかいづか",
    mean: "モースが発見した縄文時代の貝塚（東京都）",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_03",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "三内丸山遺跡",
    kana: "さんないまるやまいせき",
    mean: "最大500人規模の縄文時代の大集落遺跡（青森県）",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_04",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "土偶",
    kana: "どぐう",
    mean: "魔よけ・豊作を祈ってつくられた土の人形",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_05",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "登呂遺跡",
    kana: "とろいせき",
    mean: "弥生時代の水田・住居跡（静岡県）",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_06",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "銅鐸",
    kana: "どうたく",
    mean: "祭りの道具として使われた、鐘の形の青銅器",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_07",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "環濠集落",
    kana: "かんごうしゅうらく",
    mean: "敵の侵入に備え、まわりに濠をめぐらせた集落",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_08",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "邪馬台国",
    kana: "やまたいこく",
    mean: "3世紀、30ほどの国を従えていた国",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_09",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "縄文時代",
    kana: "じょうもんじだい",
    mean: "土器や竪穴住居が使われた、1万年以上続いた時代",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_10",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "竪穴住居",
    kana: "たてあなじゅうきょ",
    mean: "縄文・弥生時代の、地面を掘り下げてつくった住居",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_11",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "貝塚",
    kana: "かいづか",
    mean: "縄文時代、貝がらなどが積み上げられたごみ捨て場",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_12",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "稲作",
    kana: "いなさく",
    mean: "縄文時代の終わりごろに伝わった、米づくり",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_13",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "弥生土器",
    kana: "やよいどき",
    mean: "うすくてかたく、赤褐色の土器",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_14",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "石包丁",
    kana: "いしぼうちょう",
    mean: "弥生時代、稲の穂をつみとるための石器",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_15",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "高床倉庫",
    kana: "たかゆかそうこ",
    mean: "収穫した米を保存した、床を高くした建物",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_16",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "吉野ヶ里遺跡",
    kana: "よしのがりいせき",
    mean: "日本最大級の環濠集落遺跡（佐賀県）",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_17",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "『漢書』地理志",
    kana: "かんじょちりし",
    mean: "倭が100あまりの小国に分かれていたと記す中国の歴史書",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_18",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "金印",
    kana: "きんいん",
    mean: "倭の奴国の王が後漢の皇帝から授けられたもの",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_19",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "『後漢書』東夷伝",
    kana: "ごかんじょとういでん",
    mean: "奴国の王が金印を授けられたことを記す中国の歴史書",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_20",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "『魏志』倭人伝",
    kana: "ぎしわじんでん",
    mean: "邪馬台国や卑弥呼のことを記す中国の歴史書",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_21",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "縄文土器",
    kana: "じょうもんどき",
    mean: "縄目の文様がついた、縄文時代の土器",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_22",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "漢委奴国王",
    kana: "かんのわのなのこくおう",
    mean: "金印に刻まれた文字",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_23",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "倭",
    kana: "わ",
    mean: "中国の歴史書に記された、当時の日本のよび名",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_24",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "卑弥呼",
    kana: "ひみこ",
    mean: "邪馬台国の女王",
    kai: 1,
    priority: "高",
    level: "標準"
  },
  {
    id: "k1_25",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "銅剣",
    kana: "どうけん",
    mean: "祭りの道具として使われた、剣の形の青銅器",
    kai: 1,
    priority: "高",
    level: "標準"
  },
  {
    id: "k1_26",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "群馬県",
    kana: "ぐんまけん",
    mean: "岩宿遺跡がある県",
    kai: 1,
    priority: "高",
    level: "発展"
  },
  {
    id: "k1_27",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "青森県",
    kana: "あおもりけん",
    mean: "三内丸山遺跡がある県",
    kai: 1,
    priority: "高",
    level: "発展"
  },
  {
    id: "k1_28",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "野尻湖",
    kana: "のじりこ",
    mean: "ナウマンゾウの化石が出土した湖（長野県）",
    kai: 1,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k1_29",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "貧富",
    kana: "ひんぷ",
    mean: "米づくりが広まり、たくわえの差から生まれた差",
    kai: 1,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k1_30",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "金属器",
    kana: "きんぞくき",
    mean: "稲作とともに伝わった、鉄器や青銅器の総称",
    kai: 1,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k1_31",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "沖縄",
    kana: "おきなわ",
    mean: "稲作が広まったころ、北海道とともにまだ稲作が行われなかった地域",
    kai: 1,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k1_32",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "豪族",
    kana: "ごうぞく",
    mean: "むらを従えて力をもつようになった有力者",
    kai: 1,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k1_33",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "奴国",
    kana: "なこく",
    mean: "1世紀半ば、中国に使いを送り金印を授けられた国",
    kai: 1,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k1_34",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "磨製石器",
    kana: "ませいせっき",
    mean: "縄文時代、表面をみがいてつくられた石器",
    kai: 1,
    priority: "中",
    level: "標準"
  },
  {
    id: "k1_35",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "福岡県",
    kana: "ふくおかけん",
    mean: "漢委奴国王の金印が発見された志賀島がある県",
    kai: 1,
    priority: "中",
    level: "標準"
  },
  {
    id: "k1_36",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "身分",
    kana: "みぶん",
    mean: "貧富の差とともに生まれた、人々の上下関係",
    kai: 1,
    priority: "中",
    level: "標準"
  },
  {
    id: "k1_37",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "祭器",
    kana: "さいき",
    mean: "祭りの道具として使われた青銅器の総称",
    kai: 1,
    priority: "中",
    level: "標準"
  },
  {
    id: "k1_38",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "打製石器",
    kana: "だせいせっき",
    mean: "旧石器時代、石を打ち欠いてつくった道具",
    kai: 1,
    priority: "中",
    level: "発展"
  },
  {
    id: "k1_39",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "臼と杵",
    kana: "うすときね",
    mean: "収穫した稲を脱穀するのに使った道具",
    kai: 1,
    priority: "中",
    level: "発展"
  },
  {
    id: "k1_40",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "交易",
    kana: "こうえき",
    mean: "縄文時代、足りないものを物々交換でおぎなう活動",
    kai: 1,
    priority: "低",
    level: "基礎"
  },
  // ========================================
  // 第2回：古墳時代・飛鳥時代 (43語)
  // ========================================
  {
    id: "k2_01",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "前方後円墳",
    kana: "ぜんぽうこうえんふん",
    mean: "かぎ穴のような形をした古墳",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_02",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "埴輪",
    kana: "はにわ",
    mean: "古墳のまわりや頂上に置かれた素焼きの土製品",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_03",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "渡来人",
    kana: "とらいじん",
    mean: "中国・朝鮮半島から日本に渡り、技術や文化を伝えた人々",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_04",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "推古天皇",
    kana: "すいこてんのう",
    mean: "聖徳太子が政治をたすけた、最初の女性天皇",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_05",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "冠位十二階",
    kana: "かんいじゅうにかい",
    mean: "能力や手柄に応じて役人に位をあたえたしくみ",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_06",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "憲法十七条",
    kana: "けんぽうじゅうしちじょう",
    mean: "役人としての心がまえを示したきまり",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_07",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "小野妹子",
    kana: "おののいもこ",
    mean: "607年に遣隋使として派遣された人物",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_08",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "法隆寺",
    kana: "ほうりゅうじ",
    mean: "現存する世界最古の木造建築で、聖徳太子が建てたとされる寺院",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_09",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "大化の改新",
    kana: "たいかのかいしん",
    mean: "645年に始まった政治の改革",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_10",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "大仙古墳",
    kana: "だいせんこふん",
    mean: "大阪府堺市にある日本最大の古墳",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_11",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "儒教",
    kana: "じゅきょう",
    mean: "5世紀に百済から伝えられた、孔子の教え",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_12",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "仏教",
    kana: "ぶっきょう",
    mean: "6世紀に百済から公に伝えられた、インドのシャカの教え",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_13",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "百済",
    kana: "くだら",
    mean: "儒教・仏教を公に日本に伝えた国",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_14",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "蘇我",
    kana: "そが",
    mean: "6世紀に勢力を強め、聖徳太子の死後は天皇をしのぐほどになった氏族",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_15",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "聖徳太子",
    kana: "しょうとくたいし",
    mean: "推古天皇の摂政となり、政治のしくみを整えた人物",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_16",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "摂政",
    kana: "せっしょう",
    mean: "天皇をたすけて政治を行う役職",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_17",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "隋",
    kana: "ずい",
    mean: "遣隋使が派遣された中国の王朝",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_18",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "遣隋使",
    kana: "けんずいし",
    mean: "隋の進んだ制度や文化を取り入れるための使節",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_19",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "唐",
    kana: "とう",
    mean: "618年に成立した強大な中国の王朝",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_20",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "飛鳥",
    kana: "あすか",
    mean: "聖徳太子のころに栄えた、日本最初の仏教文化の名の由来となった地",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_21",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "中大兄皇子",
    kana: "なかのおおえのおうじ",
    mean: "中臣鎌足とともに蘇我氏を倒した人物（後の天智天皇）",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_22",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "中臣鎌足",
    kana: "なかとみのかまたり",
    mean: "中大兄皇子とともに蘇我氏を倒した人物",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_23",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "壬申の乱",
    kana: "じんしんのらん",
    mean: "天智天皇の後つぎをめぐり672年に起こった戦い",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_24",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "持統天皇",
    kana: "じとうてんのう",
    mean: "694年に藤原京をきずいた天皇",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_25",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "古墳",
    kana: "こふん",
    mean: "大王や豪族の墓としてつくられた、3世紀後半から7世紀ごろまでのもり土",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_26",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "飛鳥文化",
    kana: "あすかぶんか",
    mean: "法隆寺に代表される、日本で最初の仏教文化",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_27",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "藤原京",
    kana: "ふじわらきょう",
    mean: "持統天皇が奈良盆地にきずいた本格的な都",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_28",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "厩戸皇子",
    kana: "うまやどのおうじ",
    mean: "聖徳太子のもう一つの名",
    kai: 2,
    priority: "高",
    level: "標準"
  },
  {
    id: "k2_29",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "天智天皇",
    kana: "てんじてんのう",
    mean: "白村江の戦いのあと即位した中大兄皇子の名",
    kai: 2,
    priority: "高",
    level: "発展"
  },
  {
    id: "k2_30",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "ワカタケル大王",
    kana: "わかたけるだいおう",
    mean: "江田船山古墳・稲荷山古墳の鉄刀・鉄剣に名が刻まれた大王",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_31",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "白村江の戦い",
    kana: "はくすきのえのたたかい",
    mean: "663年、日本が唐と新羅の連合軍に敗れた戦い",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_32",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "天武天皇",
    kana: "てんむてんのう",
    mean: "壬申の乱に勝って位についた天皇",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_33",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "富本銭",
    kana: "ふほんせん",
    mean: "日本で最初につくられた銅銭",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_34",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "大王",
    kana: "だいおう",
    mean: "ヤマト政権を中心となってまとめた、後の天皇にあたる存在",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_35",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "豪族",
    kana: "ごうぞく",
    mean: "ヤマト政権のもとで、それぞれ氏をつくっていた有力者",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_36",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "江田船山古墳",
    kana: "えたふなやまこふん",
    mean: "ワカタケル大王の名が刻まれた鉄刀が出土した古墳（熊本県）",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_37",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "稲荷山古墳",
    kana: "いなりやまこふん",
    mean: "ワカタケル大王の名が刻まれた鉄剣が出土した古墳（埼玉県）",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_38",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "氏姓制度",
    kana: "しせいせいど",
    mean: "豪族が氏をつくり、家柄に応じて姓をあたえられたヤマト政権のしくみ",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_39",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "養蚕",
    kana: "ようさん",
    mean: "渡来人が伝えた、蚕を飼ってまゆをとる技術",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_40",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "新羅",
    kana: "しらぎ",
    mean: "唐と結んで百済を滅ぼした国",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_41",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "大津",
    kana: "おおつ",
    mean: "白村江の戦いのあと中大兄皇子が都を移した地",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_42",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "高句麗",
    kana: "こうくり",
    mean: "4世紀の終わりごろヤマト政権が百済と結んで戦った、朝鮮半島北部の国",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k2_43",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "白鳳文化",
    kana: "はくほうぶんか",
    mean: "唐の初期の文化の影響を受けて栄えた文化",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  // ========================================
  // 第3回：奈良時代 (40語)
  // ========================================
  {
    id: "k3_01",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "大宝律令",
    kana: "たいほうりつりょう",
    mean: "701年、唐の制度にならって定められた法令",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_02",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "調",
    kana: "ちょう",
    mean: "地方の特産物を納める税",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_03",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "庸",
    kana: "よう",
    mean: "都で10日間働く代わりに布を納める税",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_04",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "防人",
    kana: "さきもり",
    mean: "3年間、九州の守りにつく兵士",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_05",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "平城京",
    kana: "へいじょうきょう",
    mean: "710年、唐の長安にならってつくられた都",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_06",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "聖武天皇",
    kana: "しょうむてんのう",
    mean: "743年に大仏をつくる命令を出した天皇",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_07",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "墾田永年私財法",
    kana: "こんでんえいねんしざいほう",
    mean: "743年、開墾した田を永久に私有してよいと定めた法律",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_08",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "鑑真",
    kana: "がんじん",
    mean: "苦難をのりこえて唐から来日し、日本の僧の制度を整えた人物",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_09",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "天平文化",
    kana: "てんぴょうぶんか",
    mean: "聖武天皇のころに栄えた、唐の影響が強い仏教中心の文化",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_10",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "郡司",
    kana: "ぐんじ",
    mean: "郡におかれ、その地方の豪族が任命された役人",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_11",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "戸籍",
    kana: "こせき",
    mean: "朝廷が6年ごとにつくった、人々を登録する台帳",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_12",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "班田収授",
    kana: "はんでんしゅうじゅ",
    mean: "戸籍にもとづいて口分田をあたえるしくみ",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_13",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "租",
    kana: "そ",
    mean: "口分田にかけられ、収穫の約3％の稲を納める税",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_14",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "長安",
    kana: "ちょうあん",
    mean: "平城京がならってつくられた、唐の都",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_15",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "仏教",
    kana: "ぶっきょう",
    mean: "聖武天皇が、その力で社会の不安をしずめようとした教え",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_16",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "国分寺",
    kana: "こくぶんじ",
    mean: "741年、聖武天皇が国ごとに建てるよう命じた、男性の僧のための寺",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_17",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "東大寺",
    kana: "とうだいじ",
    mean: "聖武天皇の命令で大仏がつくられた、奈良県の寺",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_18",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "大仏",
    kana: "だいぶつ",
    mean: "聖武天皇の命令で東大寺につくられた、752年完成の仏像",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_19",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "行基",
    kana: "ぎょうき",
    mean: "各地で仏の教えを説き、大仏づくりにも協力した僧",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_20",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "三世一身の法",
    kana: "さんぜいっしんのほう",
    mean: "723年、新しく開墾した土地を3代まで私有してよいと定めた法律",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_21",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "荘園",
    kana: "しょうえん",
    mean: "貴族や寺社が開墾して増やした私有地",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_22",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "遣唐使",
    kana: "けんとうし",
    mean: "唐のすすんだ制度や文化を取り入れるために送られた使節",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_23",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "唐招提寺",
    kana: "とうしょうだいじ",
    mean: "鑑真が奈良県に開いた寺",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_24",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "古事記",
    kana: "こじき",
    mean: "712年に完成した歴史書",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_25",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "日本書紀",
    kana: "にほんしょき",
    mean: "720年に完成した歴史書",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_26",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "万葉集",
    kana: "まんようしゅう",
    mean: "農民から天皇までの歌が収められた、現存する最古の和歌集",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_27",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "正倉院",
    kana: "しょうそういん",
    mean: "聖武天皇の日用品などが収められた、東大寺の倉庫",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_28",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "校倉造",
    kana: "あぜくらづくり",
    mean: "正倉院がつくられている、三角柱の木材を組む建築様式",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_29",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "和同開珎",
    kana: "わどうかいちん",
    mean: "708年につくられた貨幣",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_30",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "大宰府",
    kana: "だざいふ",
    mean: "現在の福岡県に置かれた、九州の政治・外交・防衛にあたる役所",
    kai: 3,
    priority: "高",
    level: "発展"
  },
  {
    id: "k3_31",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "阿倍仲麻呂",
    kana: "あべのなかまろ",
    mean: "8世紀初め、留学生として唐に渡り、帰国できず唐の皇帝に仕えた人物",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k3_32",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "木簡",
    kana: "もっかん",
    mean: "税として都に運ばれた品物につけられた、薄い木の札",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k3_33",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "里長",
    kana: "さとおさ",
    mean: "里で税の取り立てを行った役人",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k3_34",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "雑徭",
    kana: "ぞうよう",
    mean: "国司のもとで1年に60日以内働く労役",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k3_35",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "元明",
    kana: "げんめい",
    mean: "710年、都を平城京に移した天皇",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k3_36",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "国分尼寺",
    kana: "こくぶんにじ",
    mean: "741年、聖武天皇が国ごとに建てるよう命じた、女性の僧のための寺",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k3_37",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "貧窮問答歌",
    kana: "ひんきゅうもんどうか",
    mean: "農民の苦しいくらしをよんだ、山上憶良の歌",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k3_38",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "口分田",
    kana: "くぶんでん",
    mean: "戸籍にもとづき、6歳以上の男女にあたえられた田",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k3_39",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "貴族",
    kana: "きぞく",
    mean: "寺社とともに、農民を使って開墾し私有地を増やした有力者",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k3_40",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "風土記",
    kana: "ふどき",
    mean: "713年に編集が始められた、各国のようすをまとめたもの",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
];

// 単元一覧（ホーム画面の単元選択チップ用）
const KANJI_UNITS = [
  { key: "第1回", name: "第1回.旧石器時代・縄文時代・弥生時代", count: 40 },
  { key: "第2回", name: "第2回.古墳時代・飛鳥時代", count: 43 },
  { key: "第3回", name: "第3回.奈良時代", count: 40 },
];
