// 中学受験 社会 漢字書き取りドリル データ
// 四谷大塚 予習シリーズ5年下 準拠
// kosukequiz-battle側 data.js の KANJI_DATA と同じ内容・同じid体系（k{回}_{連番}）
// quiz_csv（社会通常回）が作成する 第{回}回_漢字.json をそのまま反映したもの

const KANJI_DATA = [
  // ========================================
  // 第1回：旧石器時代・縄文時代・弥生時代 (40語)
  // ========================================
  {
    id: "k1_02",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "大森貝塚",
    kana: "おおもりかいづか",
    mean: "モースが発見した縄文時代の貝塚（東京都）",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_03",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "三内丸山遺跡",
    kana: "さんないまるやまいせき",
    mean: "最大500人規模の縄文時代の大集落遺跡（青森県）",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_04",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "土偶",
    kana: "どぐう",
    mean: "魔よけ・豊作を祈ってつくられた土の人形",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_05",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "登呂遺跡",
    kana: "とろいせき",
    mean: "弥生時代の水田・住居跡（静岡県）",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_06",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "銅鐸",
    kana: "どうたく",
    mean: "祭りの道具として使われた、鐘の形の青銅器",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_07",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "環濠集落",
    kana: "かんごうしゅうらく",
    mean: "敵の侵入に備え、まわりに濠をめぐらせた集落",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_08",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "邪馬台国",
    kana: "やまたいこく",
    mean: "3世紀、30ほどの国を従えていた国",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_09",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "縄文時代",
    kana: "じょうもんじだい",
    mean: "土器や竪穴住居が使われた、1万年以上続いた時代",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_10",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "竪穴住居",
    kana: "たてあなじゅうきょ",
    mean: "縄文・弥生時代の、地面を掘り下げてつくった住居",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_11",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "貝塚",
    kana: "かいづか",
    mean: "縄文時代、貝がらなどが積み上げられたごみ捨て場",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_12",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "稲作",
    kana: "いなさく",
    mean: "縄文時代の終わりごろに伝わった、米づくり",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_13",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "弥生土器",
    kana: "やよいどき",
    mean: "うすくてかたく、赤褐色の土器",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_14",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "石包丁",
    kana: "いしぼうちょう",
    mean: "弥生時代、稲の穂をつみとるための石器",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_15",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "高床倉庫",
    kana: "たかゆかそうこ",
    mean: "収穫した米を保存した、床を高くした建物",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_16",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "吉野ヶ里遺跡",
    kana: "よしのがりいせき",
    mean: "日本最大級の環濠集落遺跡（佐賀県）",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_17",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "『漢書』地理志",
    kana: "かんじょちりし",
    mean: "倭が100あまりの小国に分かれていたと記す中国の歴史書",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_18",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "金印",
    kana: "きんいん",
    mean: "倭の奴国の王が後漢の皇帝から授けられたもの",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_19",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "『後漢書』東夷伝",
    kana: "ごかんじょとういでん",
    mean: "奴国の王が金印を授けられたことを記す中国の歴史書",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_20",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "『魏志』倭人伝",
    kana: "ぎしわじんでん",
    mean: "邪馬台国や卑弥呼のことを記す中国の歴史書",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_22",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "漢委奴国王",
    kana: "かんのわのなのこくおう",
    mean: "金印に刻まれた文字",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_23",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "倭",
    kana: "わ",
    mean: "中国の歴史書に記された、当時の日本のよび名",
    kai: 1,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k1_25",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "銅剣",
    kana: "どうけん",
    mean: "祭りの道具として使われた、剣の形の青銅器",
    kai: 1,
    priority: "高",
    level: "標準"
  },
  {
    id: "k1_28",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "野尻湖",
    kana: "のじりこ",
    mean: "ナウマンゾウの化石が出土した湖（長野県）",
    kai: 1,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k1_32",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "豪族",
    kana: "ごうぞく",
    mean: "むらを従えて力をもつようになった有力者",
    kai: 1,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k1_33",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "奴国",
    kana: "なこく",
    mean: "1世紀半ば、中国に使いを送り金印を授けられた国",
    kai: 1,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k1_34",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "磨製石器",
    kana: "ませいせっき",
    mean: "縄文時代、表面をみがいてつくられた石器",
    kai: 1,
    priority: "中",
    level: "標準"
  },
  {
    id: "k1_38",
    unit: "第1回.旧石器時代・縄文時代・弥生時代",
    unitKey: "第1回",
    word: "打製石器",
    kana: "だせいせっき",
    mean: "旧石器時代、石を打ち欠いてつくった道具",
    kai: 1,
    priority: "中",
    level: "発展"
  },
  // ========================================
  // 第2回：古墳時代・飛鳥時代 (43語)
  // ========================================
  {
    id: "k2_01",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "前方後円墳",
    kana: "ぜんぽうこうえんふん",
    mean: "かぎ穴のような形をした古墳",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_02",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "埴輪",
    kana: "はにわ",
    mean: "古墳のまわりや頂上に置かれた素焼きの土製品",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_03",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "渡来人",
    kana: "とらいじん",
    mean: "中国・朝鮮半島から日本に渡り、技術や文化を伝えた人々",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_04",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "推古天皇",
    kana: "すいこてんのう",
    mean: "聖徳太子が政治をたすけた、最初の女性天皇",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_05",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "冠位十二階",
    kana: "かんいじゅうにかい",
    mean: "能力や手柄に応じて役人に位をあたえたしくみ",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_06",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "憲法十七条",
    kana: "けんぽうじゅうしちじょう",
    mean: "役人としての心がまえを示したきまり",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_08",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "法隆寺",
    kana: "ほうりゅうじ",
    mean: "現存する世界最古の木造建築で、聖徳太子が建てたとされる寺院",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_09",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "大化の改新",
    kana: "たいかのかいしん",
    mean: "645年に始まった政治の改革",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_10",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "大仙古墳",
    kana: "だいせんこふん",
    mean: "大阪府堺市にある日本最大の古墳",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_13",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "百済",
    kana: "くだら",
    mean: "儒教・仏教を公に日本に伝えた国",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_15",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "聖徳太子",
    kana: "しょうとくたいし",
    mean: "推古天皇の摂政となり、政治のしくみを整えた人物",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_16",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "摂政",
    kana: "せっしょう",
    mean: "天皇をたすけて政治を行う役職",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_17",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "隋",
    kana: "ずい",
    mean: "遣隋使が派遣された中国の王朝",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_18",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "遣隋使",
    kana: "けんずいし",
    mean: "隋の進んだ制度や文化を取り入れるための使節",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_19",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "唐",
    kana: "とう",
    mean: "618年に成立した強大な中国の王朝",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_20",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "飛鳥",
    kana: "あすか",
    mean: "聖徳太子のころに栄えた、日本最初の仏教文化の名の由来となった地",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_23",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "壬申の乱",
    kana: "じんしんのらん",
    mean: "天智天皇の後つぎをめぐり672年に起こった戦い",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_25",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "古墳",
    kana: "こふん",
    mean: "大王や豪族の墓としてつくられた、3世紀後半から7世紀ごろまでのもり土",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_26",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "飛鳥文化",
    kana: "あすかぶんか",
    mean: "法隆寺に代表される、日本で最初の仏教文化",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k2_29",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "天智天皇",
    kana: "てんじてんのう",
    mean: "白村江の戦いのあと即位した中大兄皇子の名",
    kai: 2,
    priority: "高",
    level: "発展"
  },
  {
    id: "k2_35",
    unit: "第2回.古墳時代・飛鳥時代",
    unitKey: "第2回",
    word: "豪族",
    kana: "ごうぞく",
    mean: "ヤマト政権のもとで、それぞれ氏をつくっていた有力者",
    kai: 2,
    priority: "中",
    level: "基礎"
  },
  // ========================================
  // 第3回：奈良時代 (40語)
  // ========================================
  {
    id: "k3_01",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "大宝律令",
    kana: "たいほうりつりょう",
    mean: "701年、唐の制度にならって定められた法令",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_02",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "調",
    kana: "ちょう",
    mean: "地方の特産物を納める税",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_03",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "庸",
    kana: "よう",
    mean: "都で10日間働く代わりに布を納める税",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_04",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "防人",
    kana: "さきもり",
    mean: "3年間、九州の守りにつく兵士",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_05",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "平城京",
    kana: "へいじょうきょう",
    mean: "710年、唐の長安にならってつくられた都",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_07",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "墾田永年私財法",
    kana: "こんでんえいねんしざいほう",
    mean: "743年、開墾した田を永久に私有してよいと定めた法律",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_08",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "鑑真",
    kana: "がんじん",
    mean: "苦難をのりこえて唐から来日し、日本の僧の制度を整えた人物",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_12",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "班田収授",
    kana: "はんでんしゅうじゅ",
    mean: "戸籍にもとづいて口分田をあたえるしくみ",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_13",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "租",
    kana: "そ",
    mean: "口分田にかけられ、収穫の約3％の稲を納める税",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_20",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "三世一身の法",
    kana: "さんぜいっしんのほう",
    mean: "723年、新しく開墾した土地を3代まで私有してよいと定めた法律",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_21",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "荘園",
    kana: "しょうえん",
    mean: "貴族や寺社が開墾して増やした私有地",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_22",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "遣唐使",
    kana: "けんとうし",
    mean: "唐のすすんだ制度や文化を取り入れるために送られた使節",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_23",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "唐招提寺",
    kana: "とうしょうだいじ",
    mean: "鑑真が奈良県に開いた寺",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_24",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "古事記",
    kana: "こじき",
    mean: "712年に完成した歴史書",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_25",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "日本書紀",
    kana: "にほんしょき",
    mean: "720年に完成した歴史書",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_26",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "万葉集",
    kana: "まんようしゅう",
    mean: "農民から天皇までの歌が収められた、現存する最古の和歌集",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_27",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "正倉院",
    kana: "しょうそういん",
    mean: "聖武天皇の日用品などが収められた、東大寺の倉庫",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_28",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "校倉造",
    kana: "あぜくらづくり",
    mean: "正倉院がつくられている、三角柱の木材を組む建築様式",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k3_37",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "貧窮問答歌",
    kana: "ひんきゅうもんどうか",
    mean: "農民の苦しいくらしをよんだ、山上憶良の歌",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k3_38",
    unit: "第3回.奈良時代",
    unitKey: "第3回",
    word: "口分田",
    kana: "くぶんでん",
    mean: "戸籍にもとづき、6歳以上の男女にあたえられた田",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  // ========================================
  // 第4回.平安時代 (46語)
  // ========================================
  {
    id: "k4_01",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "桓武天皇",
    kana: "かんむてんのう",
    mean: "平安京に都を移し、律令政治の立て直しに努めた天皇",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_02",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "平将門の乱",
    kana: "たいらのまさかどのらん",
    mean: "10世紀前半、関東地方で起こった武士の反乱",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_03",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "藤原純友の乱",
    kana: "ふじわらのすみとものらん",
    mean: "10世紀前半、瀬戸内海で起こった反乱",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_04",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "院政",
    kana: "いんせい",
    mean: "上皇が、位をゆずった後も行った政治",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_05",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "平清盛",
    kana: "たいらのきよもり",
    mean: "平治の乱に勝利し、武士として初めて太政大臣になった人物",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_06",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "太政大臣",
    kana: "だいじょうだいじん",
    mean: "平清盛が1167年に武士として初めてついた役職",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_07",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "国風文化",
    kana: "こくふうぶんか",
    mean: "平安時代の中ごろ以降に栄えた、日本の風土にあった文化",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_08",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "紫式部",
    kana: "むらさきしきぶ",
    mean: "『源氏物語』の作者",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_09",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "枕草子",
    kana: "まくらのそうし",
    mean: "清少納言が書いた随筆",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_10",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "紀貫之",
    kana: "きのつらゆき",
    mean: "かな文字で書かれた最初の日記『土佐日記』の作者",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_11",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "平等院鳳凰堂",
    kana: "びょうどういんほうおうどう",
    mean: "京都府宇治市にある、藤原頼通が建てた阿弥陀堂",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_12",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "浄土教",
    kana: "じょうどきょう",
    mean: "阿弥陀仏を信じ、極楽浄土に行けるという教え",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_13",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "平安京",
    kana: "へいあんきょう",
    mean: "794年、桓武天皇が都を移した先",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_14",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "征夷大将軍",
    kana: "せいいたいしょうぐん",
    mean: "坂上田村麻呂が任命された、蝦夷平定のための役職",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_15",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "摂政",
    kana: "せっしょう",
    mean: "天皇が幼いときや女性のときに天皇をたすける役職",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_16",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "関白",
    kana: "かんぱく",
    mean: "天皇が成人した後も天皇をたすけて政治を行う役職",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_17",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "摂関政治",
    kana: "せっかんせいじ",
    mean: "藤原氏が摂政・関白として実権をにぎった政治",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_18",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "荘園",
    kana: "しょうえん",
    mean: "貴族や寺社がもっていた私有地",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_19",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "遣唐使",
    kana: "けんとうし",
    mean: "894年、菅原道真の提案で停止された、唐へ送られた使節",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_20",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "藤原道長",
    kana: "ふじわらのみちなが",
    mean: "摂関政治の全盛期をきずいた人物。「望月の歌」で知られる",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_21",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "源氏",
    kana: "げんじ",
    mean: "清和天皇を祖先とする有力な武士団",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_22",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "平氏",
    kana: "へいし",
    mean: "桓武天皇を祖先とする有力な武士団",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_23",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "源義家",
    kana: "みなもとのよしいえ",
    mean: "11世紀後半、東北地方の豪族の争いをしずめた武士",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_24",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "保元",
    kana: "ほうげん",
    mean: "1156年、上皇と天皇が対立して都で起こった乱",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_25",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "平治",
    kana: "へいじ",
    mean: "1159年、平清盛と源義朝が対立して起こった乱",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_26",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "大輪田泊",
    kana: "おおわだのとまり",
    mean: "平清盛が整えた、現在の神戸港の一部にあたる港",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_27",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "日宋貿易",
    kana: "にっそうぼうえき",
    mean: "平清盛が大輪田泊を整えてさかんにした、宋との貿易",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_28",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "最澄",
    kana: "さいちょう",
    mean: "天台宗を日本に伝えた人物",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_29",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "延暦寺",
    kana: "えんりゃくじ",
    mean: "最澄が比叡山に建てた寺",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_30",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "空海",
    kana: "くうかい",
    mean: "真言宗を開いた人物",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_31",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "金剛峯寺",
    kana: "こんごうぶじ",
    mean: "空海が高野山に建てた寺",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_32",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "源氏物語",
    kana: "げんじものがたり",
    mean: "紫式部が著した物語",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_33",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "寝殿造",
    kana: "しんでんづくり",
    mean: "国風文化のころの、貴族の屋敷のつくり",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_34",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "大和絵",
    kana: "やまとえ",
    mean: "やわらかな線で日本の風物を描いた絵",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_35",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "天台宗",
    kana: "てんだいしゅう",
    mean: "最澄が伝えた仏教の宗派",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_36",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "真言宗",
    kana: "しんごんしゅう",
    mean: "空海が開いた仏教の宗派",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_37",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "菅原道真",
    kana: "すがわらのみちざね",
    mean: "遣唐使の停止を提案した人物",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "k4_38",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "厳島神社",
    kana: "いつくしまじんじゃ",
    mean: "平氏一族が航海の神としてうやまった、広島県にある世界遺産の神社",
    kai: 4,
    priority: "高",
    level: "標準"
  },
  {
    id: "k4_39",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "中尊寺金色堂",
    kana: "ちゅうそんじこんじきどう",
    mean: "岩手県平泉にある、奥州藤原氏が建てた阿弥陀堂",
    kai: 4,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k4_40",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "蝦夷",
    kana: "えみし",
    mean: "東北地方に住み、坂上田村麻呂に抵抗した人々",
    kai: 4,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k4_41",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "不輸の権",
    kana: "ふゆのけん",
    mean: "荘園が獲得した、税を払わなくてもよい権利",
    kai: 4,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k4_42",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "不入の権",
    kana: "ふにゅうのけん",
    mean: "荘園が獲得した、役人の立ち入りを断る権利",
    kai: 4,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k4_43",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "平泉",
    kana: "ひらいずみ",
    mean: "奥州藤原氏が約100年間栄えた、岩手県の地名",
    kai: 4,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k4_44",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "僧兵",
    kana: "そうへい",
    mean: "大寺院が要求を通すために使った、武装した僧",
    kai: 4,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k4_45",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "源義朝",
    kana: "みなもとのよしとも",
    mean: "平治の乱で平清盛と対立した武士",
    kai: 4,
    priority: "中",
    level: "基礎"
  },
  {
    id: "k4_46",
    unit: "第4回.平安時代",
    unitKey: "第4回",
    word: "絵巻物",
    kana: "えまきもの",
    mean: "『源氏物語絵巻』など、絵と物語からなるもの",
    kai: 4,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki2_01",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "中京工業地帯",
    kana: "ちゅうきょうこうぎょうちたい",
    mean: "愛知・三重・岐阜南部に広がる、工業生産額が日本一の工業地帯",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_02",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "阪神工業地帯",
    kana: "はんしんこうぎょうちたい",
    mean: "大阪・兵庫の沿岸部を中心に和歌山県まで広がる工業地帯",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_03",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "京浜工業地帯",
    kana: "けいひんこうぎょうちたい",
    mean: "東京湾の西岸を中心とした、印刷業がさかんな工業地帯",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_04",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "印刷",
    kana: "いんさつ",
    mean: "情報が集中する首都・東京があるため京浜工業地帯で発達した工業",
    kai: 2,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki2_05",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "北九州工業地域",
    kana: "きたきゅうしゅうこうぎょうちいき",
    mean: "官営八幡製鉄所をきっかけに発達した福岡県北部の工業地域",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_06",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "八幡",
    kana: "やはた",
    mean: "1901年に生産を開始した官営製鉄所（八幡製鉄所）がある地名",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_07",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "瀬戸内工業地域",
    kana: "せとうちこうぎょうちいき",
    mean: "埋め立て地や塩田あと地を利用して発展した岡山・広島などの工業地域",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_08",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "関東内陸工業地域",
    kana: "かんとうないりくこうぎょうちいき",
    mean: "栃木・群馬・埼玉にかけて発達した工業地域",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_09",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "東海工業地域",
    kana: "とうかいこうぎょうちいき",
    mean: "静岡県に広がる、製紙・パルプ工業の生産額が日本一の工業地域",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_10",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "京葉工業地域",
    kana: "けいようこうぎょうちいき",
    mean: "千葉県の東京湾岸部を埋め立ててつくられた工業地域",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_11",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "北陸工業地域",
    kana: "ほくりくこうぎょうちいき",
    mean: "めがねわく・洋食器などの地場産業が発達した工業地域",
    kai: 2,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki2_12",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "石油危機",
    kana: "せきゆきき",
    mean: "1973年の中東戦争をきっかけに石油の価格が上がり起こったこと",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_13",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "秋田新幹線",
    kana: "あきたしんかんせん",
    mean: "東京駅と秋田駅を結ぶ新幹線",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_14",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "山形新幹線",
    kana: "やまがたしんかんせん",
    mean: "東京駅と新庄駅を結ぶ新幹線",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_15",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "上越新幹線",
    kana: "じょうえつしんかんせん",
    mean: "東京駅と新潟駅を結ぶ新幹線",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_16",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "北陸新幹線",
    kana: "ほくりくしんかんせん",
    mean: "東京駅と敦賀駅（現在の下りの終着駅）を結ぶ新幹線",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_17",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "九州新幹線",
    kana: "きゅうしゅうしんかんせん",
    mean: "博多駅と鹿児島中央駅を結ぶ新幹線",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_18",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "山陽新幹線",
    kana: "さんようしんかんせん",
    mean: "新大阪駅と博多駅を結ぶ新幹線",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_19",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "東海道新幹線",
    kana: "とうかいどうしんかんせん",
    mean: "1964年の東京オリンピックにあわせて開業した日本最初の新幹線",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_20",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "東北新幹線",
    kana: "とうほくしんかんせん",
    mean: "東京駅と新青森駅を結ぶ新幹線",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_21",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "北海道新幹線",
    kana: "ほっかいどうしんかんせん",
    mean: "新青森駅と新函館北斗駅を結ぶ新幹線",
    kai: 2,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki2_22",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "大宮",
    kana: "おおみや",
    mean: "東北・上越・北陸新幹線などが分岐する埼玉県の駅",
    kai: 2,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki2_23",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "高崎",
    kana: "たかさき",
    mean: "上越・北陸新幹線が停まる群馬県の駅",
    kai: 2,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki2_24",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "福島",
    kana: "ふくしま",
    mean: "東北・山形新幹線が停まる駅",
    kai: 2,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki2_25",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "盛岡",
    kana: "もりおか",
    mean: "東北・秋田新幹線が停まる岩手県の駅",
    kai: 2,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki2_26",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "石油",
    kana: "せきゆ",
    mean: "日本のエネルギー供給割合で最も高い資源",
    kai: 2,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki2_27",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "水力",
    kana: "すいりょく",
    mean: "ダムなどを利用した発電に使われるエネルギー",
    kai: 2,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki2_28",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "敦賀",
    kana: "つるが",
    mean: "北陸新幹線の現在の下りの終着駅がある福井県の都市",
    kai: 2,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki2_29",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "輪島塗",
    kana: "わじまぬり",
    mean: "石川県輪島市でつくられる伝統的工芸品",
    kai: 2,
    priority: "中",
    level: "発展"
  },
  {
    id: "kaki2_30",
    unit: "夏期講習 復習編2.工業・資源・輸送機関",
    unitKey: "夏期講習復習編2",
    word: "土佐和紙",
    kana: "とさわし",
    mean: "高知県でつくられる伝統的工芸品",
    kai: 2,
    priority: "中",
    level: "発展"
  },
  {
    id: "kaki3_01",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "干拓",
    kana: "かんたく",
    mean: "遠浅の海などを堤防で仕切って陸地にすること（筑紫平野など）",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_02",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "促成栽培",
    kana: "そくせいさいばい",
    mean: "ビニールハウスなどを利用して野菜の生育を早める栽培方法（宮崎平野など）",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_03",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "筑紫山地",
    kana: "つくしさんち",
    mean: "九州北部に広がる山地",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_04",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "筑紫平野",
    kana: "つくしへいや",
    mean: "干拓による耕地拡大で知られる九州最大級の平野",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_05",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "筑後川",
    kana: "ちくごがわ",
    mean: "「筑紫次郎」の別名を持つ、有明海に注ぐ川",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_06",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "雲仙岳",
    kana: "うんぜんだけ",
    mean: "長崎県にある火山",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_07",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "有明海",
    kana: "ありあけかい",
    mean: "のりの養殖や干潟で知られる九州の海",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_08",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "阿蘇山",
    kana: "あそさん",
    mean: "広大なカルデラで知られる熊本県の火山",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_09",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "九州山地",
    kana: "きゅうしゅうさんち",
    mean: "九州中央部を東西に走る山地",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_10",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "球磨川",
    kana: "くまがわ",
    mean: "日本三大急流の一つに数えられる熊本県の川",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_11",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "宮崎平野",
    kana: "みやざきへいや",
    mean: "促成栽培がさかんな宮崎県の平野",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_12",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "桜島",
    kana: "さくらじま",
    mean: "鹿児島湾にある活火山",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_13",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "薩摩半島",
    kana: "さつまはんとう",
    mean: "鹿児島県西部の半島",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_14",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "大隅半島",
    kana: "おおすみはんとう",
    mean: "桜島と陸続きになっている鹿児島県東部の半島",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_15",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "屋久島",
    kana: "やくしま",
    mean: "すぎの原生林で知られ世界自然遺産に登録されている島",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_16",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "種子島",
    kana: "たねがしま",
    mean: "鉄砲伝来の地として知られる鹿児島県の島",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_17",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "奄美大島",
    kana: "あまみおおしま",
    mean: "鹿児島県に属する南西諸島の島",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_18",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "沖縄島",
    kana: "おきなわじま",
    mean: "沖縄県で最も大きい島。北部はやんばると呼ばれる",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_19",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "西表島",
    kana: "いりおもてじま",
    mean: "世界自然遺産に登録されている沖縄県の島",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_20",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "与那国島",
    kana: "よなぐにじま",
    mean: "日本最西端に位置する島",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_21",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "機械",
    kana: "きかい",
    mean: "北九州工業地域で現在中心となっている工業（自動車生産など）",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_22",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "北九州市",
    kana: "きたきゅうしゅうし",
    mean: "福岡県にある政令指定都市（県庁所在地ではない）",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_23",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "福岡市",
    kana: "ふくおかし",
    mean: "博多駅がある福岡県の県庁所在地・政令指定都市",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_24",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "久留米市",
    kana: "くるめし",
    mean: "ゴム工業やかすり（織物）の産地として知られる福岡県の都市",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_25",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "佐賀市",
    kana: "さがし",
    mean: "佐賀県の県庁所在地",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_26",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "伊万里市",
    kana: "いまりし",
    mean: "陶磁器の産地として知られる佐賀県の都市",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_27",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "有田町",
    kana: "ありたちょう",
    mean: "陶磁器（有田焼）の産地として知られる佐賀県の町",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_28",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "佐世保市",
    kana: "させぼし",
    mean: "造船業がさかんな長崎県の都市",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_29",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "長崎市",
    kana: "ながさきし",
    mean: "造船業がさかんで西九州新幹線が通る長崎県の県庁所在地",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_30",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "大分市",
    kana: "おおいたし",
    mean: "鉄鋼業や石油化学コンビナートがある大分県の県庁所在地",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_31",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "熊本市",
    kana: "くまもとし",
    mean: "熊本県の県庁所在地・政令指定都市",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_32",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "水俣市",
    kana: "みなまたし",
    mean: "四大公害病の一つが発生した熊本県の都市",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_33",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "宮崎市",
    kana: "みやざきし",
    mean: "宮崎県の県庁所在地",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_34",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "鹿児島市",
    kana: "かごしまし",
    mean: "鹿児島県の県庁所在地",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_35",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "那覇市",
    kana: "なはし",
    mean: "沖縄県の県庁所在地",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_36",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "八代平野",
    kana: "やつしろへいや",
    mean: "い草の栽培がさかんな熊本県の平野",
    kai: 3,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki3_37",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "宮崎県",
    kana: "みやざきけん",
    mean: "きゅうり・ピーマンなど促成栽培がさかんな県",
    kai: 3,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki3_38",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "肉牛",
    kana: "にくぎゅう",
    mean: "鹿児島県などで飼育がさかんな家畜",
    kai: 3,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki3_39",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "熊野筆",
    kana: "くまのふで",
    mean: "広島県でつくられる伝統的工芸品（九州の工芸品と紛らわしい例）",
    kai: 3,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki3_40",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "有機水銀",
    kana: "ゆうきすいぎん",
    mean: "水俣病の原因となった物質",
    kai: 3,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki3_41",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "地熱",
    kana: "ちねつ",
    mean: "火山の蒸気を利用した発電方法（大分県別府など）",
    kai: 3,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki3_42",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "有田焼",
    kana: "ありたやき",
    mean: "佐賀県有田町で400年ほど前からつくられる陶磁器",
    kai: 3,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki3_43",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "沖縄県",
    kana: "おきなわけん",
    mean: "アメリカ軍基地が集中する県",
    kai: 3,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki3_44",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "熊本県",
    kana: "くまもとけん",
    mean: "阿蘇山や水俣病で知られる県",
    kai: 3,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki3_45",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "大分県",
    kana: "おおいたけん",
    mean: "地熱発電がさかんな温泉の多い県",
    kai: 3,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki3_46",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "長崎県",
    kana: "ながさきけん",
    mean: "大村湾での真珠養殖や造船業で知られる県",
    kai: 3,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki3_47",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "佐賀県",
    kana: "さがけん",
    mean: "有田焼や有明海の干潟で知られる県",
    kai: 3,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki3_48",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "福岡県",
    kana: "ふくおかけん",
    mean: "北九州工業地域と県庁所在地の2つの政令指定都市がある県",
    kai: 3,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki3_49",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "備前焼",
    kana: "びぜんやき",
    mean: "岡山県の伝統的工芸品（九州の工芸品と紛らわしい例）",
    kai: 3,
    priority: "中",
    level: "発展"
  },
  {
    id: "kaki3_50",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "対馬",
    kana: "つしま",
    mean: "朝鮮半島と古くから結びつきの強かった長崎県の島",
    kai: 3,
    priority: "中",
    level: "発展"
  },
  {
    id: "kaki3_51",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "シラス台地",
    kana: "シラスだいち",
    mean: "火山の噴出物が積もってできた九州南部の台地（笠野原など）",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki3_52",
    unit: "夏期講習 復習編3.九州地方",
    unitKey: "夏期講習復習編3",
    word: "八幡製鉄所",
    kana: "やはたせいてつじょ",
    mean: "1901年操業開始、北九州工業地域発展のきっかけとなった官営の製鉄所",
    kai: 3,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_01",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "吉野川",
    kana: "よしのがわ",
    mean: "讃岐平野の香川用水の水源で、「四国三郎」の別名を持つ川",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_02",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "促成栽培",
    kana: "そくせいさいばい",
    mean: "ビニールハウスなどを利用して野菜の生育を早める栽培方法（高知平野など）",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_03",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "中海",
    kana: "なかうみ",
    mean: "鳥取県と島根県にまたがる湖",
    kai: 4,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki4_04",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "宍道湖",
    kana: "しんじこ",
    mean: "しじみの産地として知られる島根県の湖",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_05",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "中国山地",
    kana: "ちゅうごくさんち",
    mean: "中国地方の中央部を走る山地",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_06",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "秋吉台",
    kana: "あきよしだい",
    mean: "石灰岩が雨などにとかされてできたカルスト地形で知られる山口県の地名",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_07",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "児島湾",
    kana: "こじまわん",
    mean: "岡山県にある湾",
    kai: 4,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki4_08",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "岡山平野",
    kana: "おかやまへいや",
    mean: "もも・マスカットの産地として知られる平野",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_09",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "太田川",
    kana: "おおたがわ",
    mean: "広島市内に河口がある川",
    kai: 4,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki4_10",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "広島平野",
    kana: "ひろしまへいや",
    mean: "三角州が広がる平野",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_11",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "宮島",
    kana: "みやじま",
    mean: "厳島神社（世界文化遺産）がある島",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_12",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "小豆島",
    kana: "しょうどしま",
    mean: "オリーブの産地として知られる瀬戸内海の島",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_13",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "讃岐平野",
    kana: "さぬきへいや",
    mean: "香川用水が引かれている平野",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_14",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "讃岐山脈",
    kana: "さぬきさんみゃく",
    mean: "香川県と徳島県の県境にある山脈",
    kai: 4,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki4_15",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "徳島平野",
    kana: "とくしまへいや",
    mean: "吉野川の河口に広がる平野",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_16",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "四国山地",
    kana: "しこくさんち",
    mean: "四国中央部を東西に走る山地",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_17",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "高知平野",
    kana: "こうちへいや",
    mean: "促成栽培がさかんな平野",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_18",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "四万十川",
    kana: "しまんとがわ",
    mean: "高知県を流れる、「日本最後の清流」ともよばれる川",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_19",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "宇和海",
    kana: "うわかい",
    mean: "真珠の養殖がさかんな愛媛県の海",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_20",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "生口島",
    kana: "いくちじま",
    mean: "レモンの産地として知られる瀬戸内海の島",
    kai: 4,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki4_21",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "境港",
    kana: "さかいみなと",
    mean: "日本海側有数の漁港がある鳥取県の都市",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_22",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "倉敷",
    kana: "くらしき",
    mean: "水島コンビナートで知られる岡山県の都市",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_23",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "福山",
    kana: "ふくやま",
    mean: "鉄鋼業がさかんな広島県の都市",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_24",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "呉",
    kana: "くれ",
    mean: "造船業がさかんな広島県の都市",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_25",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "山口",
    kana: "やまぐち",
    mean: "山口県の県庁所在地",
    kai: 4,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki4_26",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "宇部",
    kana: "うべ",
    mean: "セメント工業がさかんな山口県の都市",
    kai: 4,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki4_27",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "下関",
    kana: "しものせき",
    mean: "関門トンネルがある山口県の都市",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_28",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "今治",
    kana: "いまばり",
    mean: "タオルの生産で知られる愛媛県の都市",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_29",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "三角州",
    kana: "さんかくす",
    mean: "川が運んだ土砂が河口に積もってできる地形（広島平野など）",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_30",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "石灰石",
    kana: "せっかいせき",
    mean: "セメント工業の原料となる岩石",
    kai: 4,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki4_31",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "厳島神社",
    kana: "いつくしまじんじゃ",
    mean: "広島県宮島にある世界文化遺産の神社",
    kai: 4,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki4_32",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "徳島県",
    kana: "とくしまけん",
    mean: "中国・四国地方の分県図（A〜H）のいずれにもあてはまらない県",
    kai: 4,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki4_33",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "松江市",
    kana: "まつえし",
    mean: "島根県の県庁所在地（県名と異なる例）",
    kai: 4,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki4_34",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "松山市",
    kana: "まつやまし",
    mean: "愛媛県の県庁所在地（県名と異なる例）",
    kai: 4,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki4_35",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "高松市",
    kana: "たかまつし",
    mean: "香川県の県庁所在地（県名と異なる例）",
    kai: 4,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki4_36",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "広島市",
    kana: "ひろしまし",
    mean: "政令指定都市、原爆ドームがある",
    kai: 4,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki4_37",
    unit: "夏期講習 復習編4.中国・四国地方",
    unitKey: "夏期講習復習編4",
    word: "岡山市",
    kana: "おかやまし",
    mean: "政令指定都市、後楽園がある",
    kai: 4,
    priority: "高",
    level: "標準"
  },

  // ========================================
  // 夏期講習 復習編5.近畿地方 (54語)
  // ========================================
  {
    id: "kaki5_01",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "若狭湾",
    kana: "わかさわん",
    mean: "福井県から京都府にかけて広がる、リアス海岸が見られる湾",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_02",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "天橋立",
    kana: "あまのはしだて",
    mean: "京都府北部にある日本三景の1つ",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_03",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "琵琶湖",
    kana: "びわこ",
    mean: "滋賀県にある日本最大の湖。京阪神の水がめとよばれる",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_04",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "伊勢湾",
    kana: "いせわん",
    mean: "三重県と愛知県にはさまれた湾",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_05",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "鈴鹿山脈",
    kana: "すずかさんみゃく",
    mean: "滋賀県と三重県の境にある山脈",
    kai: 5,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki5_06",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "近江盆地",
    kana: "おうみぼんち",
    mean: "琵琶湖の周りに広がる盆地",
    kai: 5,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki5_07",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "京都盆地",
    kana: "きょうとぼんち",
    mean: "京都市が広がる盆地",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_08",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "淀川",
    kana: "よどがわ",
    mean: "琵琶湖から流れ出て大阪湾に注ぐ川。上流では瀬田川・宇治川とよばれる",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_09",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "大阪平野",
    kana: "おおさかへいや",
    mean: "淀川の下流に広がる、近郊農業がさかんだった平野",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_10",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "大阪湾",
    kana: "おおさかわん",
    mean: "沿岸に阪神工業地帯が広がる湾",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_11",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "淡路島",
    kana: "あわじしま",
    mean: "瀬戸内海で最大の面積をもつ島。たまねぎの栽培がさかん",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_12",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "紀伊山地",
    kana: "きいさんち",
    mean: "三重・奈良・和歌山の3県にまたがる山地。林業がさかん",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_13",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "奈良盆地",
    kana: "ならぼんち",
    mean: "奈良県北部に広がる盆地",
    kai: 5,
    priority: "中",
    level: "基礎"
  },
  {
    id: "kaki5_14",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "紀の川",
    kana: "きのかわ",
    mean: "和歌山県北部を流れ、有田川とともに流域でみかんの栽培がさかんな川。上流は吉野川",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_15",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "志摩半島",
    kana: "しまはんとう",
    mean: "三重県にある、リアス海岸が見られる半島",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_16",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "英虞湾",
    kana: "あごわん",
    mean: "志摩半島にある、真珠の養殖がさかんな湾",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_17",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "熊野川",
    kana: "くまのがわ",
    mean: "新宮川ともよばれ、流域にすぎやひのきの森林が広がる川",
    kai: 5,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki5_18",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "紀伊半島",
    kana: "きいはんとう",
    mean: "近畿地方の南部に大きく突き出た半島",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_19",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "有田川",
    kana: "ありだがわ",
    mean: "紀の川とともに、和歌山県北部でみかんの栽培がさかんな流域をつくる川",
    kai: 5,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki5_20",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "吉野川",
    kana: "よしのがわ",
    mean: "紀の川の上流にあたる、奈良県を流れる川",
    kai: 5,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki5_21",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "丹波高地",
    kana: "たんばこうち",
    mean: "京都府と兵庫県にまたがる高地",
    kai: 5,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki5_22",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "五ヶ所湾",
    kana: "ごかしょわん",
    mean: "英虞湾とともに真珠の養殖が行われている、志摩半島の湾",
    kai: 5,
    priority: "低",
    level: "標準"
  },
  {
    id: "kaki5_23",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "滋賀県",
    kana: "しがけん",
    mean: "琵琶湖がある、海に面していない県",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_24",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "三重県",
    kana: "みえけん",
    mean: "志摩半島や伊勢神宮がある県",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_25",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "兵庫県",
    kana: "ひょうごけん",
    mean: "近畿地方で最も面積が広い県。淡路島がふくまれる",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_26",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "和歌山県",
    kana: "わかやまけん",
    mean: "みかん・柿・うめの生産量が日本一の県",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_27",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "奈良県",
    kana: "ならけん",
    mean: "海に面しておらず、吉野すぎの林業がさかんな県",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_28",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "大津市",
    kana: "おおつし",
    mean: "滋賀県の県庁所在地",
    kai: 5,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki5_29",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "京都市",
    kana: "きょうとし",
    mean: "西陣織・京友禅・清水焼で知られる政令指定都市",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_30",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "宇治市",
    kana: "うじし",
    mean: "京都府南部にあり、高級品として有名な茶を生産している都市",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_31",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "神戸市",
    kana: "こうべし",
    mean: "兵庫県の県庁所在地。ポートアイランドがある",
    kai: 5,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki5_32",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "明石市",
    kana: "あかしし",
    mean: "日本標準時子午線が通っている兵庫県の都市",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_33",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "姫路市",
    kana: "ひめじし",
    mean: "世界文化遺産の城がある兵庫県の都市",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_34",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "四日市市",
    kana: "よっかいちし",
    mean: "石油化学工業がさかんで、四大公害病の1つが発生した三重県の都市",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_35",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "津市",
    kana: "つし",
    mean: "三重県の県庁所在地",
    kai: 5,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki5_36",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "堺市",
    kana: "さかいし",
    mean: "石油化学工業がさかんな、大阪府の政令指定都市",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_37",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "尾鷲市",
    kana: "おわせし",
    mean: "年間4000mmに近い降水量で知られる三重県の都市",
    kai: 5,
    priority: "低",
    level: "標準"
  },
  {
    id: "kaki5_38",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "門真市",
    kana: "かどまし",
    mean: "電気機器の工場が集まる大阪府の都市",
    kai: 5,
    priority: "低",
    level: "標準"
  },
  {
    id: "kaki5_39",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "近郊農業",
    kana: "きんこうのうぎょう",
    mean: "大都市の近くで野菜などをつくり、新鮮なうちに出荷する農業",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_40",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "阪神工業地帯",
    kana: "はんしんこうぎょうちたい",
    mean: "大阪湾の沿岸部を中心とした工業地帯。金属工業の割合が高い",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_41",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "政令指定都市",
    kana: "せいれいしていとし",
    mean: "人口50万人以上で、都道府県なみの仕事を任されている市",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_42",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "西陣織",
    kana: "にしじんおり",
    mean: "京都市で生産されている伝統的な絹織物",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_43",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "清水焼",
    kana: "きよみずやき",
    mean: "京都市で生産されている伝統的な焼き物",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_44",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "日本標準時子午線",
    kana: "にほんひょうじゅんじしごせん",
    mean: "東経135度の経線。日本の時刻の基準",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_45",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "姫路城",
    kana: "ひめじじょう",
    mean: "白鷺城ともよばれる世界文化遺産の城",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_46",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "関西国際空港",
    kana: "かんさいこくさいくうこう",
    mean: "大阪湾の海上につくられた、24時間利用できる空港",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_47",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "真珠",
    kana: "しんじゅ",
    mean: "英虞湾や五ヶ所湾で養殖されているもの",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_48",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "養殖",
    kana: "ようしょく",
    mean: "たまごや稚魚から育てて出荷する漁業",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_49",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "季節風",
    kana: "きせつふう",
    mean: "夏と冬で吹く向きが変わる風",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_50",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "伊勢神宮",
    kana: "いせじんぐう",
    mean: "三重県にある神社",
    kai: 5,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki5_51",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "東大寺",
    kana: "とうだいじ",
    mean: "奈良県にある、大仏で知られる寺",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_52",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "明石海峡大橋",
    kana: "あかしかいきょうおおはし",
    mean: "本州と淡路島を結んでいる橋",
    kai: 5,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki5_53",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "大鳴門橋",
    kana: "おおなるときょう",
    mean: "淡路島と徳島県を結んでいる橋",
    kai: 5,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki5_54",
    unit: "夏期講習 復習編5.近畿地方",
    unitKey: "夏期講習復習編5",
    word: "紀州備長炭",
    kana: "きしゅうびんちょうたん",
    mean: "和歌山県の伝統的な地場産品である木炭",
    kai: 5,
    priority: "低",
    level: "発展"
  },

  // ========================================
  // 夏期講習 復習編6.中部地方 (71語)
  // ========================================
  {
    id: "kaki6_01",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "佐渡島",
    kana: "さどがしま",
    mean: "新潟県にある、世界文化遺産の金山とときで知られる島",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_02",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "越後平野",
    kana: "えちごへいや",
    mean: "信濃川の下流に広がる、米の単作地帯として知られる平野",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_03",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "阿賀野川",
    kana: "あがのがわ",
    mean: "下流域で新潟水俣病が発生した、新潟県の川",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_04",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "信濃川",
    kana: "しなのがわ",
    mean: "日本一長い川。新潟市で日本海に注ぐ",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_05",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "能登半島",
    kana: "のとはんとう",
    mean: "石川県から日本海に突き出た、輪島塗で知られる半島",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_06",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "越後山脈",
    kana: "えちごさんみゃく",
    mean: "新潟県と福島県・群馬県の境をなす山脈",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_07",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "長野盆地",
    kana: "ながのぼんち",
    mean: "善光寺があり、りんごの栽培がさかんな盆地",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_08",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "飛驒山脈",
    kana: "ひださんみゃく",
    mean: "北アルプスともよばれる山脈",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_09",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "神通川",
    kana: "じんづうがわ",
    mean: "流域でイタイイタイ病が発生した、富山県の川",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_10",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "関東山地",
    kana: "かんとうさんち",
    mean: "中部地方と関東地方の境にある山地",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_11",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "八ヶ岳",
    kana: "やつがたけ",
    mean: "東側の山ろくに野辺山原が広がる、長野県と山梨県の境の山",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_12",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "諏訪湖",
    kana: "すわこ",
    mean: "天竜川の水源となっている、長野県の湖",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_13",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "若狭湾",
    kana: "わかさわん",
    mean: "リアス海岸が見られ、原子力発電所が集まっている湾",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_14",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "甲府盆地",
    kana: "こうふぼんち",
    mean: "ぶどう・ももの栽培がさかんな、山梨県の盆地",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_15",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "富士山",
    kana: "ふじさん",
    mean: "世界文化遺産に登録された、日本一高い山",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_16",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "伊豆半島",
    kana: "いずはんとう",
    mean: "静岡県の東部にある半島",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_17",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "富士川",
    kana: "ふじかわ",
    mean: "日本三大急流の1つに数えられる川",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_18",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "赤石山脈",
    kana: "あかいしさんみゃく",
    mean: "南アルプスともよばれる山脈",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_19",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "牧ノ原",
    kana: "まきのはら",
    mean: "静岡県にある、茶の栽培がさかんな台地",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_20",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "木曽山脈",
    kana: "きそさんみゃく",
    mean: "中央アルプスともよばれる、ひのきの美林で知られる山脈",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_21",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "天竜川",
    kana: "てんりゅうがわ",
    mean: "諏訪湖を水源とし、遠州灘に注ぐ川",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_22",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "浜名湖",
    kana: "はまなこ",
    mean: "うなぎの養殖で知られてきた、静岡県の湖",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_23",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "渥美半島",
    kana: "あつみはんとう",
    mean: "豊川用水が引かれ、電照菊の栽培で知られる半島",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_24",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "木曽川",
    kana: "きそがわ",
    mean: "長良川・揖斐川とともに濃尾平野を流れる川",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_25",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "長良川",
    kana: "ながらがわ",
    mean: "木曽三川の1つで、鵜飼いでも知られる川",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_26",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "濃尾平野",
    kana: "のうびへいや",
    mean: "輪中が見られる、名古屋市が位置する平野",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_27",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "知多半島",
    kana: "ちたはんとう",
    mean: "愛知県から伊勢湾と三河湾をへだてる半島",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_28",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "野辺山原",
    kana: "のべやまはら",
    mean: "八ヶ岳の東側にある、高原野菜の栽培がさかんな高原",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_29",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "高冷地農業",
    kana: "こうれいちのうぎょう",
    mean: "すずしい気候をいかして高原で野菜をつくる農業",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_30",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "単作",
    kana: "たんさく",
    mean: "1年に1種類の作物だけをつくること",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_31",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "輪中",
    kana: "わじゅう",
    mean: "洪水を防ぐため、集落や田畑を堤防で囲んだ地域",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_32",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "北陸地方",
    kana: "ほくりくちほう",
    mean: "中部地方の日本海側の地域",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_33",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "中京工業地帯",
    kana: "ちゅうきょうこうぎょうちたい",
    mean: "愛知県を中心とする、生産額が全国一の工業地帯",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_34",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "東海工業地域",
    kana: "とうかいこうぎょうちいき",
    mean: "静岡県に広がる工業地域",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_35",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "北陸工業地域",
    kana: "ほくりくこうぎょうちいき",
    mean: "伝統工業が発達している、日本海側の工業地域",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_36",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "上越新幹線",
    kana: "じょうえつしんかんせん",
    mean: "東京駅と新潟駅を結ぶ新幹線",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_37",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "東名高速道路",
    kana: "とうめいこうそくどうろ",
    mean: "東海工業地域を通る高速道路",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_38",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "新潟市",
    kana: "にいがたし",
    mean: "信濃川の河口にある、中部地方で最も北の政令指定都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_39",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "富山市",
    kana: "とやまし",
    mean: "製薬（くすりの生産）で知られる都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_40",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "輪島市",
    kana: "わじまし",
    mean: "漆器（輪島塗）の生産で知られる、能登半島の都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_41",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "金沢市",
    kana: "かなざわし",
    mean: "加賀百万石の城下町として栄え、兼六園がある都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_42",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "福井市",
    kana: "ふくいし",
    mean: "福井県の県庁所在地",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_43",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "敦賀市",
    kana: "つるがし",
    mean: "原子力発電所がある、福井県の都市",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_44",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "長野市",
    kana: "ながのし",
    mean: "善光寺の門前町として発達した都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_45",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "岡谷市",
    kana: "おかやし",
    mean: "諏訪湖の西岸にあり、製糸業から精密機械工業へ移り変わった都市",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_46",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "諏訪市",
    kana: "すわし",
    mean: "精密機械工業・電子工業がさかんな、長野県の都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_47",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "甲府市",
    kana: "こうふし",
    mean: "山梨県の県庁所在地",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_48",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "富士市",
    kana: "ふじし",
    mean: "製紙・パルプ工業がさかんな、静岡県の都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_49",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "静岡市",
    kana: "しずおかし",
    mean: "静岡県の県庁所在地で、政令指定都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_50",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "焼津市",
    kana: "やいづし",
    mean: "まぐろ・かつおの遠洋漁業の基地として知られる都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_51",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "浜松市",
    kana: "はままつし",
    mean: "楽器・オートバイの生産で知られる、静岡県の政令指定都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_52",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "瀬戸市",
    kana: "せとし",
    mean: "多治見市とともに陶磁器の生産で知られる、愛知県の都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_53",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "豊田市",
    kana: "とよたし",
    mean: "矢作川流域にある、日本最大の自動車工業都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_54",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "岐阜市",
    kana: "ぎふし",
    mean: "岐阜県の県庁所在地",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_55",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "一宮市",
    kana: "いちのみやし",
    mean: "毛織物の生産で知られる、愛知県の都市",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_56",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "東海市",
    kana: "とうかいし",
    mean: "鉄鋼の生産がさかんな、愛知県の都市",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_57",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "名古屋市",
    kana: "なごやし",
    mean: "濃尾平野の南端にある、中京工業地帯の中心の政令指定都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_58",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "四日市市",
    kana: "よっかいちし",
    mean: "石油化学コンビナートがあり、ぜんそくの公害が発生した都市",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_59",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "燕市",
    kana: "つばめし",
    mean: "洋食器の生産で知られる、新潟県の都市",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_60",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "小千谷市",
    kana: "おぢやし",
    mean: "小千谷ちぢみの生産で知られる、新潟県の都市",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_61",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "多治見市",
    kana: "たじみし",
    mean: "瀬戸市とともに陶磁器の生産で知られる、岐阜県の都市",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_62",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "加賀友禅",
    kana: "かがゆうぜん",
    mean: "金沢市で生産されている伝統的な染め物",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_63",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "九谷焼",
    kana: "くたにやき",
    mean: "石川県で生産されている伝統的な焼き物",
    kai: 6,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki6_64",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "兼六園",
    kana: "けんろくえん",
    mean: "金沢市にある、日本三名園の1つ",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_65",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "善光寺",
    kana: "ぜんこうじ",
    mean: "長野市にある寺。門前町として発達した",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_66",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "養蚕",
    kana: "ようさん",
    mean: "かいこを飼って生糸のもとになるまゆをとること",
    kai: 6,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki6_67",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "製糸業",
    kana: "せいしぎょう",
    mean: "まゆから生糸をつくる工業",
    kai: 6,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki6_68",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "精密機械工業",
    kana: "せいみつきかいこうぎょう",
    mean: "時計やカメラなど、細かい部品を組み立てる工業",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_69",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "陶磁器",
    kana: "とうじき",
    mean: "瀬戸市・多治見市で生産がさかんな焼き物",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_70",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "遠洋漁業",
    kana: "えんようぎょぎょう",
    mean: "遠くの海まで出かけて、長い期間行う漁業",
    kai: 6,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki6_71",
    unit: "夏期講習 復習編6.中部地方",
    unitKey: "夏期講習復習編6",
    word: "駿河湾",
    kana: "するがわん",
    mean: "焼津市が面している、静岡県の湾",
    kai: 6,
    priority: "高",
    level: "基礎"
  },

  // ========================================
  // 夏期講習 復習編7.関東地方 (58語)
  // ========================================
  {
    id: "kaki7_01",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "越後山脈",
    kana: "えちごさんみゃく",
    mean: "関東地方と新潟県の境にある山脈",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_02",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "渡良瀬川",
    kana: "わたらせがわ",
    mean: "足尾銅山鉱毒事件が起こった、利根川の支流",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_03",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "関東平野",
    kana: "かんとうへいや",
    mean: "日本最大の平野",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_04",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "浅間山",
    kana: "あさまやま",
    mean: "群馬県と長野県の境にある火山",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_05",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "霞ヶ浦",
    kana: "かすみがうら",
    mean: "茨城県にある、日本で2番目に大きい湖",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_06",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "利根川",
    kana: "とねがわ",
    mean: "流域面積が日本一で、坂東太郎ともよばれる川",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_07",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "関東山地",
    kana: "かんとうさんち",
    mean: "関東平野の南西部を南北にのびる山地",
    kai: 7,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki7_08",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "荒川",
    kana: "あらかわ",
    mean: "奥秩父を源とし、秩父盆地を流れて東京湾に注ぐ川",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_09",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "武蔵野",
    kana: "むさしの",
    mean: "関東ロームにおおわれた、東京都西部の台地",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_10",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "多摩川",
    kana: "たまがわ",
    mean: "東京都と神奈川県の境を流れ、東京湾に注ぐ川",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_11",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "九十九里浜",
    kana: "くじゅうくりはま",
    mean: "千葉県にある、単調な海岸線が続く浜",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_12",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "下総台地",
    kana: "しもうさだいち",
    mean: "千葉県北部に広がる台地",
    kai: 7,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki7_13",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "房総半島",
    kana: "ぼうそうはんとう",
    mean: "千葉県南部にある半島",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_14",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "三浦半島",
    kana: "みうらはんとう",
    mean: "神奈川県にあり、浦賀水道をはさんで房総半島と向かい合う半島",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_15",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "大島",
    kana: "おおしま",
    mean: "三原山がある、伊豆諸島最大の島",
    kai: 7,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki7_16",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "伊豆諸島",
    kana: "いずしょとう",
    mean: "東京都に属する、大島や八丈島をふくむ島々",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_17",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "小笠原諸島",
    kana: "おがさわらしょとう",
    mean: "東京都に属する世界自然遺産の島々",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_18",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "関東ローム",
    kana: "かんとうろーむ",
    mean: "関東地方の台地をおおう、火山灰からできた赤土の層",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_19",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "近郊農業",
    kana: "きんこうのうぎょう",
    mean: "大都市の近くで野菜などをつくり、新鮮なうちに出荷する農業",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_20",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "水郷",
    kana: "すいごう",
    mean: "利根川の下流域に広がる低湿地",
    kai: 7,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki7_21",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "嬬恋村",
    kana: "つまごいむら",
    mean: "群馬県にある、高冷地農業でキャベツの栽培がさかんな村",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_22",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "高冷地農業",
    kana: "こうれいちのうぎょう",
    mean: "夏でもすずしい高原の気候を利用して野菜をつくる農業",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_23",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "屋敷森",
    kana: "やしきもり",
    mean: "関東地方の内陸部で、家の周りに植えられている防風林",
    kai: 7,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki7_24",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "京浜工業地帯",
    kana: "けいひんこうぎょうちたい",
    mean: "東京湾の西岸に沿った工業地帯。印刷業がさかん",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_25",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "京葉工業地域",
    kana: "けいようこうぎょうちいき",
    mean: "化学工業の割合が最も高い、千葉県の工業地域",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_26",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "関東内陸工業地域",
    kana: "かんとうないりくこうぎょうちいき",
    mean: "栃木・群馬・埼玉の3県にまたがる工業地域",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_27",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "鹿島臨海工業地域",
    kana: "かしまりんかいこうぎょうちいき",
    mean: "掘り込み港である鹿島港を中心とした工業地域",
    kai: 7,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki7_28",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "東海村",
    kana: "とうかいむら",
    mean: "日本で初めて原子力発電が行われた茨城県の村",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_29",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "水戸市",
    kana: "みとし",
    mean: "茨城県の県庁所在地。偕楽園がある",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_30",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "偕楽園",
    kana: "かいらくえん",
    mean: "水戸市にある、日本三名園の1つ",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_31",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "鹿嶋市",
    kana: "かしまし",
    mean: "鉄鋼業がさかんな茨城県の都市",
    kai: 7,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki7_32",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "宇都宮市",
    kana: "うつのみやし",
    mean: "栃木県の県庁所在地",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_33",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "太田市",
    kana: "おおたし",
    mean: "自動車工業がさかんな群馬県の都市",
    kai: 7,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki7_34",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "前橋市",
    kana: "まえばしし",
    mean: "群馬県の県庁所在地",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_35",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "銚子市",
    kana: "ちょうしし",
    mean: "水あげ量の多い漁港がある千葉県の都市",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_36",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "成田市",
    kana: "なりたし",
    mean: "貿易額が日本一の空港がある千葉県の都市",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_37",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "千葉市",
    kana: "ちばし",
    mean: "幕張新都心がある、千葉県の県庁所在地",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_38",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "市原市",
    kana: "いちはらし",
    mean: "石油化学工業がさかんな千葉県の都市",
    kai: 7,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki7_39",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "君津市",
    kana: "きみつし",
    mean: "鉄鋼業がさかんな千葉県の都市",
    kai: 7,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki7_40",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "秩父市",
    kana: "ちちぶし",
    mean: "石灰石を産出し、セメントの生産で知られる埼玉県の都市",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_41",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "川崎市",
    kana: "かわさきし",
    mean: "石油化学工業がさかんな神奈川県の政令指定都市",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_42",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "横浜市",
    kana: "よこはまし",
    mean: "みなとみらい21がある、神奈川県の県庁所在地",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_43",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "横須賀市",
    kana: "よこすかし",
    mean: "自動車工業・造船業がさかんな神奈川県の都市",
    kai: 7,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki7_44",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "相模原市",
    kana: "さがみはらし",
    mean: "神奈川県にある政令指定都市",
    kai: 7,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki7_45",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "日光",
    kana: "にっこう",
    mean: "世界文化遺産の社寺がある栃木県の地名",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_46",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "富岡製糸場",
    kana: "とみおかせいしじょう",
    mean: "群馬県にある世界文化遺産の製糸工場",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_47",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "桐生",
    kana: "きりゅう",
    mean: "絹織物の生産で知られる群馬県の都市",
    kai: 7,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki7_48",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "石灰石",
    kana: "せっかいせき",
    mean: "秩父などで産出され、日本国内で100％自給できる地下資源",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_49",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "鉄鉱石",
    kana: "てっこうせき",
    mean: "鉄鋼の原料で、オーストラリアからの輸入が最も多い",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_50",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "上越新幹線",
    kana: "じょうえつしんかんせん",
    mean: "東京駅と新潟駅を結ぶ新幹線",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_51",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "北陸新幹線",
    kana: "ほくりくしんかんせん",
    mean: "高崎で分かれて金沢・敦賀へ向かう新幹線",
    kai: 7,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki7_52",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "東京湾アクアライン",
    kana: "とうきょうわんあくあらいん",
    mean: "川崎市と木更津市を結ぶ、東京湾を横断する道路",
    kai: 7,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki7_53",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "成田国際空港",
    kana: "なりたこくさいくうこう",
    mean: "貿易額が日本で最も多い空港",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_54",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "排他的経済水域",
    kana: "はいたてきけいざいすいいき",
    mean: "沿岸から200海里以内の、水産資源や鉱産資源を利用できる水域",
    kai: 7,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki7_55",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "沖ノ鳥島",
    kana: "おきのとりしま",
    mean: "東京都に属する日本最南端の島",
    kai: 7,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki7_56",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "印刷業",
    kana: "いんさつぎょう",
    mean: "情報が集中する東京でさかんな工業",
    kai: 7,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki7_57",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "谷津干潟",
    kana: "やつひがた",
    mean: "ラムサール条約に登録されている千葉県の干潟",
    kai: 7,
    priority: "低",
    level: "発展"
  },
  {
    id: "kaki7_58",
    unit: "夏期講習 復習編7.関東地方",
    unitKey: "夏期講習復習編7",
    word: "矢木沢",
    kana: "やぎさわ",
    mean: "利根川の上流にあるダムの名",
    kai: 7,
    priority: "低",
    level: "発展"
  },

  // ========================================
  // 夏期講習 復習編8.東北地方／北海道地方 (73語)
  // ========================================
  {
    id: "kaki8_01",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "下北半島",
    kana: "しもきたはんとう",
    mean: "青森県にある、本州最北端の半島",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_02",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "陸奥湾",
    kana: "むつわん",
    mean: "ほたて貝の養殖がさかんな、青森県の湾",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_03",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "津軽半島",
    kana: "つがるはんとう",
    mean: "青函トンネルが通る、青森県の半島",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_04",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "津軽平野",
    kana: "つがるへいや",
    mean: "りんごの栽培がさかんな青森県の平野",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_05",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "白神山地",
    kana: "しらかみさんち",
    mean: "ぶなの原生林で知られる世界自然遺産の山地",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_06",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "十和田湖",
    kana: "とわだこ",
    mean: "青森県と秋田県の境にあるカルデラ湖",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_07",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "北上高地",
    kana: "きたかみこうち",
    mean: "岩手県の東部に広がる高地",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_08",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "北上盆地",
    kana: "きたかみぼんち",
    mean: "岩手県の内陸にある盆地",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_09",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "田沢湖",
    kana: "たざわこ",
    mean: "秋田県にある、日本で最も深い湖",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_10",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "男鹿半島",
    kana: "おがはんとう",
    mean: "八郎潟の付け根にある、秋田県の半島",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_11",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "秋田平野",
    kana: "あきたへいや",
    mean: "雄物川の下流に広がる平野",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_12",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "三陸海岸",
    kana: "さんりくかいがん",
    mean: "南部がリアス海岸になっている、東北地方の太平洋岸",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_13",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "北上川",
    kana: "きたかみがわ",
    mean: "岩手県・宮城県を南へ流れ、太平洋に注ぐ川",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_14",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "仙台平野",
    kana: "せんだいへいや",
    mean: "宮城県に広がる、稲作がさかんな平野",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_15",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "奥羽山脈",
    kana: "おううさんみゃく",
    mean: "日本一長く、東北地方を南北に走る山脈",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_16",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "出羽山地",
    kana: "でわさんち",
    mean: "奥羽山脈の西側を南北に走る山地",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_17",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "最上川",
    kana: "もがみがわ",
    mean: "日本三大急流の1つで、庄内平野から日本海に注ぐ川",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_18",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "庄内平野",
    kana: "しょうないへいや",
    mean: "最上川の下流に広がる、稲作がさかんな山形県の平野",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_19",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "牡鹿半島",
    kana: "おしかはんとう",
    mean: "かきの養殖がさかんな、宮城県の半島",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_20",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "松島",
    kana: "まつしま",
    mean: "宮城県にある日本三景の1つ",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_21",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "阿武隈川",
    kana: "あぶくまがわ",
    mean: "福島盆地を流れ、宮城県で太平洋に注ぐ川",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_22",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "山形盆地",
    kana: "やまがたぼんち",
    mean: "おうとうの栽培がさかんな盆地",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_23",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "福島盆地",
    kana: "ふくしまぼんち",
    mean: "ももの栽培がさかんな盆地",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_24",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "郡山盆地",
    kana: "こおりやまぼんち",
    mean: "安積疏水が引かれた福島県の盆地",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_25",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "猪苗代湖",
    kana: "いなわしろこ",
    mean: "安積疏水の水源となっている、福島県の湖",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_26",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "八郎潟",
    kana: "はちろうがた",
    mean: "干拓されて大潟村になった、秋田県の湖",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_27",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "大潟村",
    kana: "おおがたむら",
    mean: "八郎潟を干拓してつくられた、秋田県の村",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_28",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "干拓",
    kana: "かんたく",
    mean: "遠浅の海や湖を堤防で仕切り、水をぬいて陸地にすること",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_29",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "南部鉄器",
    kana: "なんぶてっき",
    mean: "盛岡市でつくられている伝統的工芸品",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_30",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "天童将棋駒",
    kana: "てんどうしょうぎごま",
    mean: "山形県天童市でつくられている伝統的工芸品",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_31",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "会津塗",
    kana: "あいづぬり",
    mean: "福島県でつくられている伝統的工芸品の漆器",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_32",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "六ヶ所村",
    kana: "ろっかしょむら",
    mean: "核燃料再処理施設がある、青森県の村",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_33",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "八戸市",
    kana: "はちのへし",
    mean: "セメント工業と漁港で知られる青森県の都市",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_34",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "青森市",
    kana: "あおもりし",
    mean: "ねぶたで知られ、東北新幹線の終点がある都市",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_35",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "盛岡市",
    kana: "もりおかし",
    mean: "岩手県の県庁所在地。南部鉄器で知られる",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_36",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "秋田市",
    kana: "あきたし",
    mean: "竿燈で知られる秋田県の県庁所在地",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_37",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "仙台市",
    kana: "せんだいし",
    mean: "七夕と杜の都で知られる、東北地方唯一の政令指定都市",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_38",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "山形市",
    kana: "やまがたし",
    mean: "山形県の県庁所在地",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_39",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "福島市",
    kana: "ふくしまし",
    mean: "福島県の県庁所在地",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_40",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "秋田すぎ",
    kana: "あきたすぎ",
    mean: "米代川上流にみられる三大美林の1つ",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_41",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "津軽ひば",
    kana: "つがるひば",
    mean: "津軽半島にある日本三大美林の1つ",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_42",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "竿燈",
    kana: "かんとう",
    mean: "秋田市で行われる東北三大祭りの1つ",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_43",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "平泉",
    kana: "ひらいずみ",
    mean: "中尊寺金色堂を中心とする岩手県の世界文化遺産",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_44",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "冷害",
    kana: "れいがい",
    mean: "夏の低温で稲などが不作になること",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_45",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "知床半島",
    kana: "しれとこはんとう",
    mean: "世界自然遺産に登録されている北海道の半島",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_46",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "サロマ湖",
    kana: "さろまこ",
    mean: "ほたて貝の養殖がさかんな北海道の湖",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_47",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "大雪山",
    kana: "たいせつざん",
    mean: "北海道の中央部にある山",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_48",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "上川盆地",
    kana: "かみかわぼんち",
    mean: "旭川市が位置する、稲作がさかんな盆地",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_49",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "石狩川",
    kana: "いしかりがわ",
    mean: "上川盆地を流れ、日本海に注ぐ北海道最大の川",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_50",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "石狩平野",
    kana: "いしかりへいや",
    mean: "客土によって稲作がさかんになった北海道の平野",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_51",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "根室半島",
    kana: "ねむろはんとう",
    mean: "北海道の東端にある半島",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_52",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "根釧台地",
    kana: "こんせんだいち",
    mean: "酪農がさかんな北海道東部の台地",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_53",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "十勝平野",
    kana: "とかちへいや",
    mean: "てんさい・じゃがいもなどの畑作がさかんな平野",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_54",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "日高山脈",
    kana: "ひだかさんみゃく",
    mean: "北海道の南部を南北に走る山脈",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_55",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "有珠山",
    kana: "うすざん",
    mean: "洞爺湖のそばにある北海道の火山",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_56",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "渡島半島",
    kana: "おしまはんとう",
    mean: "北海道の南西部にある半島",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_57",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "択捉島",
    kana: "えとろふとう",
    mean: "北方領土のうち最も大きい島",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_58",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "国後島",
    kana: "くなしりとう",
    mean: "北方領土の1つで、択捉島の南西にある島",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_59",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "北方領土",
    kana: "ほっぽうりょうど",
    mean: "択捉島・国後島・色丹島・歯舞群島のこと",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_60",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "旭川市",
    kana: "あさひかわし",
    mean: "上川盆地にある、製紙・パルプ工業がさかんな都市",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_61",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "釧路市",
    kana: "くしろし",
    mean: "日本有数の漁港がある北海道の都市",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_62",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "帯広市",
    kana: "おびひろし",
    mean: "十勝平野の中心にある都市",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_63",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "札幌市",
    kana: "さっぽろし",
    mean: "雪まつりで知られる、北海道唯一の政令指定都市",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_64",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "千歳市",
    kana: "ちとせし",
    mean: "国際空港があり、電子工業がさかんな北海道の都市",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_65",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "苫小牧市",
    kana: "とまこまいし",
    mean: "掘り込み港があり、製紙・パルプ工業がさかんな都市",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_66",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "室蘭市",
    kana: "むろらんし",
    mean: "鉄鋼業がさかんな北海道の都市",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_67",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "函館市",
    kana: "はこだてし",
    mean: "水産加工がさかんな、渡島半島の都市",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_68",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "稚内市",
    kana: "わっかないし",
    mean: "日本最北の都市",
    kai: 8,
    priority: "中",
    level: "標準"
  },
  {
    id: "kaki8_69",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "酪農",
    kana: "らくのう",
    mean: "乳牛を飼い、牛乳や乳製品をつくる農業",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_70",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "輪作",
    kana: "りんさく",
    mean: "同じ畑で年ごとに種類のちがう作物を順につくること",
    kai: 8,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki8_71",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "青函トンネル",
    kana: "せいかんとんねる",
    mean: "北海道と津軽半島を結ぶ鉄道専用の海底トンネル",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
  {
    id: "kaki8_72",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "蝦夷地",
    kana: "えぞち",
    mean: "北海道の昔のよび名",
    kai: 8,
    priority: "高",
    level: "標準"
  },
  {
    id: "kaki8_73",
    unit: "夏期講習 復習編8.東北地方／北海道地方",
    unitKey: "夏期講習復習編8",
    word: "津波",
    kana: "つなみ",
    mean: "地震によって起こり、リアス海岸で高くなりやすい災害",
    kai: 8,
    priority: "高",
    level: "基礎"
  },
];

// 単元一覧（ホーム画面の単元選択チップ用）
const KANJI_UNITS = [
  { key: "第1回", name: "第1回.旧石器時代・縄文時代・弥生時代", count: 27 },
  { key: "第2回", name: "第2回.古墳時代・飛鳥時代", count: 21 },
  { key: "第3回", name: "第3回.奈良時代", count: 20 },
  { key: "第4回", name: "第4回.平安時代", count: 46 },
  { key: "夏期講習復習編2", name: "夏期講習 復習編2.工業・資源・輸送機関", count: 30 },
  { key: "夏期講習復習編3", name: "夏期講習 復習編3.九州地方", count: 52 },
  { key: "夏期講習復習編4", name: "夏期講習 復習編4.中国・四国地方", count: 37 },
  { key: "夏期講習復習編5", name: "夏期講習 復習編5.近畿地方", count: 54 },
  { key: "夏期講習復習編6", name: "夏期講習 復習編6.中部地方", count: 71 },
  { key: "夏期講習復習編7", name: "夏期講習 復習編7.関東地方", count: 58 },
  { key: "夏期講習復習編8", name: "夏期講習 復習編8.東北地方／北海道地方", count: 73 },
];
